### ISSUE TITLE
Shortcut error gohome

### ISSUE THREAD

**Issue by kovika** [twilsonco/OpenPilotSiriShortcuts#1]
Hi, 

i made the authenticaton, but I got error.
Ios 17

Kcl.errordomain

is it because of wrong settings?

Thank You

**Comment by twilsonco** [comment]
Can you be more specific? So you setup your jwt token I take it. ~~Which shortcut are you using that’s giving issues?~~ What steps to get the error?

**Comment by twilsonco** [comment]
I tested out the shortcuts a bit tonight and they're working fine for me. I suspect the location you're using for your home address in the "go to home" shortcut is triggering an iOS Shortcuts bug. There's several bugs I've encountered resulting in variants of that error message, all having to do with location-based shortcut actions. I've never posted about it, but for example:
1. What does the error (kCLErrorDomain error 2.) mean? : r/shortcuts — https://www.reddit.com/r/shortcuts/comments/134kr72/what_does_the_error_kclerrordomain_error_2_mean/
2. iOS bug in passing location data (and workaround) : r/shortcuts — https://www.reddit.com/r/shortcuts/comments/sfwi91/ios_bug_in_passing_location_data_and_workaround/
3. KCL error domain error 8? : r/iosshortcuts — https://www.reddit.com/r/iosshortcuts/comments/14itq8o/kcl_error_domain_error_8/

Not to sound like an Apple CSR, but have you updated to the latest iOS? If the error persists, you can DM (on discord, in the [comma.ai server](https://discord.comma.ai), to twilsonco) me the address you're using and I can look into it.
