### ISSUE TITLE
Navigate with OpenPilot

### ISSUE THREAD

**Issue by dbzx6r** [twilsonco/OpenPilotSiriShortcuts#2]
I have Navigate with OpenPilot configured, and I am getting a Syntax error when running it. 

I am on iOS 18 developer beta so a i'm not sure if this is an iOS specific issue or not.

![image](https://github.com/twilsonco/OpenPilotSiriShortcuts/assets/81520155/1f65b7ba-d7ef-482f-91fd-d1a46e1c161c)

**Comment by twilsonco** [comment]
I'll address this. Seems that updater stopped working... As a workaround, you can disable update checking. 
![CleanShot 2024-06-12 at 12 14 29](https://github.com/twilsonco/OpenPilotSiriShortcuts/assets/7284371/538e755d-c00c-4a08-9e67-448f0abe9f9b)

**Comment by twilsonco** [comment]
A new version's been released. Should be good.
